CREATE TABLE `users` (
    `id` INT(20) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `email` VARCHAR(254) NOT NULL,
    `first_name` VARCHAR(100) NOT NULL,
    `last_name` VARCHAR(100) NOT NULL,
    `password` TEXT NOT NULL,
    `gender` INT(1),
    `is_active` INT(1),
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);